server:
  port: 8091
spring:
  application:
    name: producer
  kafka:
    bootstrap-servers: 10.10.10.100:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

logging:
  level:
    com.example.producer: debug